ingress:
  hosts:
    - host: knowledge-flow-backend.dev.fred.thalesgroup.com
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  enabled: true
  extraEnvVars:
  - name: OPENSEARCH_USER
    value: "admin"
  - name: OPENSEARCH_PASSWORD
    value: "*****"

configuration:
  vector_storage:
    username: "admin"
    password: "*****"

  tabular_storage:
    username: "admin"
    password: "*****"

  catalog_storage:
    username: "admin"
    password: "*****"


kubeconfig:
  data:
    kubeconfig: |
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0******
          server: https://127.0.0.1:6443
        name: default
      contexts:
      - context:
          cluster: default
          user: default
        name: default
      current-context: default
      kind: Config
      preferences: {}
      users:
      - name: default
        user:
          client-certificate-data: LS0********
          client-key-data: LS0*********